modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="legendmagic"
version="1.0.0"
displayName="Legend Magic"
authors="Delphy"
description='''
Lightning magic mod
'''

[[dependencies.legendmagic]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.legendmagic]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.legendmagic]]
modId="curios"
mandatory=true
versionRange="[5.14,)"
ordering="NONE"
side="BOTH"
